In [ ]:


import numpy as np
from typing import Union, Tuple, List
from abc import ABC, abstractmethod
from basic import * 


In [1]:
import torch

# 创建一个形状为 (3,) 的输入张量
x = torch.tensor([1, 2, 3])

# 广播为形状为 (2, 3) 的二维张量
broadcasted_x = torch.broadcast_to(x, (2, 3))
print(broadcasted_x.shape)  # 输出: torch.Size([2, 3])
print(broadcasted_x)
"""
输出:
tensor([[1, 2, 3],
        [1, 2, 3]])
"""

# 创建一个形状为 (2, 1) 的输入张量
y = torch.tensor([[4], 
                  [5]])

# 广播为形状为 (2, 3) 的二维张量
broadcasted_y = torch.broadcast_to(y, (2, 3))
print(broadcasted_y.shape)  # 输出: torch.Size([2, 3])
print(broadcasted_y)
"""
输出:
tensor([[4, 4, 4],
        [5, 5, 5]])
"""


torch.Size([2, 3])
tensor([[1, 2, 3],
        [1, 2, 3]])
torch.Size([2, 3])
tensor([[4, 4, 4],
        [5, 5, 5]])


'\n输出:\ntensor([[4, 4, 4],\n        [5, 5, 5]])\n'

In [11]:
import numpy as np
a = np.random.random([2,1,6])
b = np.random.random([6,1])
(a+b).shape

(2, 6, 6)